import type { OrganizationUserRole } from '../schemas/organization.schema';
import type { Permission } from './list';


/**
 * Role to permissions mapping.
 * Each role has an explicit list of permissions - no inheritance.
 */
export const ROLE_PERMISSIONS: Record<OrganizationUserRole, readonly Permission[]> = {
  OWNER: [
    'auth:read-self',
    'auth:change-password',
    'auth:logout',
    'org:list',
    'org:read',
    'org:create',
    'org:update',
    'org:switch',
    'org:invite',
    'user:list',
    'user:read',
    'user:create',
    'user:update',
    'user:delete',
    'user:create-owner',
    'user:promote-owner',
    'user:remove-owner',
    'job:create',
    'notification:list',
    'notification:read',
    'notification:update',
    'notification:delete',
    'settings:read',
    'settings:update',
    'project:list',
    'project:read',
    'project:create',
    'project:update',
    'project:delete',
    'task:list',
    'task:read',
    'task:create',
    'task:update',
    'task:delete',
    'task:transition',
    'task:merge',
    'task:comment',
    'research:read',
    'research:create',
    'research:update',
    'research:accept',
    'research:delete',
    'attachment:create',
    'attachment:list',
    'attachment:read',
    'attachment:delete',
  ],
  ADMIN: [
    'auth:read-self',
    'auth:change-password',
    'auth:logout',
    'org:list',
    'org:read',
    'org:create',
    'org:switch',
    'org:invite',
    'user:list',
    'user:read',
    'user:create',
    'user:update',
    'user:delete',
    'job:create',
    'notification:list',
    'notification:read',
    'notification:update',
    'notification:delete',
    'settings:read',
    'settings:update',
    'project:list',
    'project:read',
    'project:create',
    'project:update',
    'project:delete',
    'task:list',
    'task:read',
    'task:create',
    'task:update',
    'task:delete',
    'task:transition',
    'task:merge',
    'task:comment',
    'research:read',
    'research:create',
    'research:update',
    'research:accept',
    'research:delete',
    'attachment:create',
    'attachment:list',
    'attachment:read',
    'attachment:delete',
  ],
  MEMBER: [
    'auth:read-self',
    'auth:change-password',
    'auth:logout',
    'org:list',
    'org:read',
    'org:create',
    'org:switch',
    'notification:list',
    'notification:read',
    'notification:update',
    'notification:delete',
    'settings:read',
    // Members work tasks but do not delete work products or projects.
    'project:list',
    'project:read',
    'task:list',
    'task:read',
    'task:create',
    'task:update',
    'task:transition',
    'task:comment',
    // Members drive research end to end (create, converse, accept) but do not
    // delete work products — the same withholding as project/task:delete.
    'research:read',
    'research:create',
    'research:update',
    'research:accept',
    'attachment:create',
    'attachment:list',
    'attachment:read',
    'attachment:delete',
  ],
} as const;
